const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'src');
const files = fs.readdirSync(srcDir);

files.forEach(file => {
    if (file.endsWith('.gs')) {
        const jsName = file.replace('.gs', '.js');
        const jsPath = path.join(srcDir, jsName);
        if (fs.existsSync(jsPath)) {
            console.log(`Deleting autogenerated ${jsName}...`);
            fs.unlinkSync(jsPath);
        }
    }
});
