/**
 * EPT-OMR Project: APP_SCHEMAS Configuration (Server-Side)
 *
 * This object is the Single Source of Truth for the FormEngine.
 *
 * [E31] TOPOLOGY_PRESETS: Named catalog of reusable topology rule sets.
 * Entities reference a preset by key instead of redeclaring inline blocks.
 * All presets are frozen (immutable) to prevent accidental mutation.
 */

var TOPOLOGY_PRESETS = Object.freeze({

  /**
   * Standard hierarchical topology for graph-linked business entities.
   * Used by: Unidad_Negocio, Portafolio, Grupo_Productos, Producto
   */
  JERARQUICA_ESTRICTA_GRAPH_STD: Object.freeze({
    _preset: 'JERARQUICA_ESTRICTA_GRAPH_STD',  // [E31] Studio Viewer identifier
    topologyType: "JERARQUICA_ESTRICTA",
    preventCycles: true,
    maxDepth: 9,
    allowOrphanStealing: true,
    deletionStrategy: "ORPHAN",
    siblingCollisionCheck: true,
    scd2Enabled: true
  }),

  /**
   * Hierarchical topology for taxonomy domain entities.
   * Enforces level filtering and strict level jumps.
   * Used by: Dominio
   */
  JERARQUICA_ESTRICTA_DOMAIN: Object.freeze({
    _preset: 'JERARQUICA_ESTRICTA_DOMAIN',  // [E31] Studio Viewer identifier
    topologyType: "JERARQUICA_ESTRICTA",
    levelFiltering: true,
    strictLevelJumps: true,
    rootRequiresNoParent: true,
    allowOrphanStealing: true,
    maxDepth: 8,
    deletionStrategy: "ORPHAN",
    siblingCollisionCheck: true,
    scd2Enabled: true,
    preventCycles: true
  }),

  /**
   * Minimal hierarchical topology for person-to-person leadership graph.
   * No orphan stealing, no deletion strategy, sibling checks disabled.
   * Used by: Persona
   */
  JERARQUICA_PERSONA: Object.freeze({
    _preset: 'JERARQUICA_PERSONA',  // [E31] Studio Viewer identifier
    topologyType: "JERARQUICA_ESTRICTA",
    preventCycles: true,
    maxDepth: 15,
    scd2Enabled: true,
    siblingCollisionCheck: false
  })

});

/**
 * [E31] FIELD_TEMPLATES: Composable field factories for common repeated patterns.
 *
 * Usage (spread into fields array):
 *   fields: [
 *     { name: "id_entity", type: "hidden", primaryKey: true },
 *     ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
 *     ...FIELD_TEMPLATES.AUDIT_FIELDS(),
 *     ...FIELD_TEMPLATES.VERSION_FIELD(),
 *     // ← entity-specific fields below
 *   ]
 *
 * All factories return frozen arrays — immutable source, safe for spread.
 */
var FIELD_TEMPLATES = Object.freeze({

  /**
   * Identity Name field.
   * Standardizes the semantic name of any entity.
   */
  NAME_FIELD: (label = "Nombre", width = 12) => Object.freeze([
    { name: "nombre", type: "text", label: label, required: true, width: width, unique: true, gridOrder: 4 }
  ]),

  /**
   * Identity fields: user-friendly ID + status.
   * Universal for all business entities.
   * - lexical_id: prefix-acronym + consecutive (e.g. "PORT-0042"). Generated by Engine_DB.
   * - estado: lifecycle status flag ("Activo" | "Eliminado" | "Borrador").
   */
  SYSTEM_FIELDS: () => Object.freeze([
    {
      name: "lexical_id", type: "text", label: "ID", uiBehavior: "badge", readonly: true,
      helpText: "Generado automáticamente: ACRONIMO-CONSECUTIVO (ej. PORT-0042)", gridOrder: 3
    },
    { name: "estado", type: "hidden", defaultValue: "Activo" }
  ]),

  /**
   * Standalone status field for non-business entities (system/config tables)
   * that don't use lexical_id.
   */
  ESTADO_FIELD: () => Object.freeze([
    { name: "estado", type: "hidden", defaultValue: "Activo" }
  ]),

  /**
   * Industry-standard audit trail fields.
   * All hidden — managed exclusively by Engine_DB. Never rendered by FormEngine.
   * Provides full creation, modification, and soft-delete traceability.
   */
  AUDIT_FIELDS: () => Object.freeze([
    { name: "created_at", type: "hidden", readonly: true },
    { name: "created_by", type: "hidden", readonly: true },
    { name: "updated_at", type: "hidden", readonly: true },
    { name: "updated_by", type: "hidden", readonly: true },
    { name: "deleted_at", type: "hidden", readonly: true },
    { name: "deleted_by", type: "hidden", readonly: true }
  ]),

  /**
   * Optimistic locking version counter.
   * Incremented by Engine_DB on every write. Prevents lost-update on concurrent edits.
   * Default: 1 (first write).
   */
  VERSION_FIELD: () => Object.freeze([
    { name: "_version", type: "hidden", readonly: true, defaultValue: 1 }
  ]),

  /**
   * Standard graph topology section separator.
   * Returns a frozen single-element array (consistent with other FIELD_TEMPLATES factories).
   * Use with spread: ...FIELD_TEMPLATES.GRAPH_SEPARATOR()
   * @param {string} [label="Pertenencia Topológica (Grafo)"] - Section label
   */
  GRAPH_SEPARATOR: (label = "Pertenencia Topológica (Grafo)") => Object.freeze([
    { name: "separator_grafo", type: "divider", label, width: 12 }
  ])

});

var APP_SCHEMAS = {
Sys_Graph_Edges: {,
Sys_Cache_Signals: {,
Sys_Roles: {,
Sys_Permissions: {
};

function getAppSchema(entityName) {
  const isTaxonomiaContext = typeof window !== 'undefined' && window.taxonomiaContext;

  const applyGovernance = (schema) => {
    if (!schema || !schema.fields) return schema;

    // Deep clone the fields array to avoid mutating global definition
    const clonedSchema = Object.assign({}, schema);
    clonedSchema.fields = schema.fields.map(field => {
      // E55 Governance: Topological fields are readonly
      if (field.type === 'relation' && field.graphEntity === 'Sys_Graph_Edges') {
        // Schema-Driven Governance Exemption (S57.4)
        const isExemptEntity = schema.metadata && schema.metadata.governancePolicy === 'exempt_from_strict_readonly';
        
        if (!isTaxonomiaContext && !isExemptEntity) {
          const clonedField = Object.assign({}, field);
          clonedField.readonly = true;
          clonedField.helpText = (clonedField.helpText ? clonedField.helpText + ' ' : '') + '(Solo lectura: Gestionado vía Canvas de Taxonomía)';
          return clonedField;
        }
      }
      return field;
    });
    return clonedSchema;
  };

  if (entityName) {
    return applyGovernance(APP_SCHEMAS[entityName]);
  } else {
    const clonedSchemas = {};
    for (const key in APP_SCHEMAS) {
      if (key !== '_UI_CONFIG' && APP_SCHEMAS[key] && APP_SCHEMAS[key].fields) {
        clonedSchemas[key] = applyGovernance(APP_SCHEMAS[key]);
      } else {
        clonedSchemas[key] = APP_SCHEMAS[key];
      }
    }
    return clonedSchemas;
  }
}

/**
 * Epic E8: Safe getter for topology rules. Returns the configured rules
 * for the entity if available, otherwise returns a safe default (FLAT).
 * Prevents downstream failures for legacy entities.
 */
function getEntityTopologyRules(entityName) {
  const schema = getAppSchema(entityName);
  if (schema && schema.topologyRules) {
    return schema.topologyRules;
  }
  // Safe Fallback defaults
  return {
    topologyType: "FLAT",
    levelFiltering: false,
    strictLevelJumps: false,
    rootRequiresNoParent: false,
    allowOrphanStealing: false,
    maxDepth: 0,
    deletionStrategy: "ORPHAN", // Always default to a safe setting (no cascading)
    siblingCollisionCheck: false,
    scd2Enabled: false,
    preventCycles: false
  };
}

if (typeof module !== 'undefined') {
  module.exports = { APP_SCHEMAS, TOPOLOGY_PRESETS, FIELD_TEMPLATES, getAppSchema, getEntityTopologyRules };
}

// ─── [E31] Admin GAS endpoints ───────────────────────────────────────────────
// Requires: Adapter_Sheets_Provisioner.gs (shares GAS global scope)
// These endpoints are now maintained in API_Admin.gs for SRP.
// See API_Admin.gs for getSchemaProvisioningStatus() and runSchemaReconcile().

