/**
 * EPT-OMR Project: APP_SCHEMAS Configuration (Server-Side)
 *
 * This object is the Single Source of Truth for the FormEngine.
 *
 * [E31] TOPOLOGY_PRESETS: Named catalog of reusable topology rule sets.
 * Entities reference a preset by key instead of redeclaring inline blocks.
 * All presets are frozen (immutable) to prevent accidental mutation.
 */

var TOPOLOGY_PRESETS = Object.freeze({

  /**
   * Standard hierarchical topology for graph-linked business entities.
   * Used by: Unidad_Negocio, Portafolio, Grupo_Productos, Producto
   */
  JERARQUICA_ESTRICTA_GRAPH_STD: Object.freeze({
    _preset: 'JERARQUICA_ESTRICTA_GRAPH_STD',  // [E31] Studio Viewer identifier
    topologyType: "JERARQUICA_ESTRICTA",
    preventCycles: true,
    maxDepth: 9,
    allowOrphanStealing: true,
    deletionStrategy: "ORPHAN",
    siblingCollisionCheck: true,
    scd2Enabled: true
  }),

  /**
   * Hierarchical topology for taxonomy domain entities.
   * Enforces level filtering and strict level jumps.
   * Used by: Dominio
   */
  JERARQUICA_ESTRICTA_DOMAIN: Object.freeze({
    _preset: 'JERARQUICA_ESTRICTA_DOMAIN',  // [E31] Studio Viewer identifier
    topologyType: "JERARQUICA_ESTRICTA",
    levelFiltering: true,
    strictLevelJumps: true,
    rootRequiresNoParent: true,
    allowOrphanStealing: true,
    maxDepth: 8,
    deletionStrategy: "ORPHAN",
    siblingCollisionCheck: true,
    scd2Enabled: true,
    preventCycles: true
  }),

  /**
   * Minimal hierarchical topology for person-to-person leadership graph.
   * No orphan stealing, no deletion strategy, sibling checks disabled.
   * Used by: Persona
   */
  JERARQUICA_PERSONA: Object.freeze({
    _preset: 'JERARQUICA_PERSONA',  // [E31] Studio Viewer identifier
    topologyType: "JERARQUICA_ESTRICTA",
    preventCycles: true,
    maxDepth: 15,
    scd2Enabled: true,
    siblingCollisionCheck: false
  })

});

/**
 * [E31] FIELD_TEMPLATES: Composable field factories for common repeated patterns.
 *
 * Usage (spread into fields array):
 *   fields: [
 *     { name: "id_entity", type: "hidden", primaryKey: true },
 *     ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
 *     ...FIELD_TEMPLATES.AUDIT_FIELDS(),
 *     ...FIELD_TEMPLATES.VERSION_FIELD(),
 *     // ← entity-specific fields below
 *   ]
 *
 * All factories return frozen arrays — immutable source, safe for spread.
 */
var FIELD_TEMPLATES = Object.freeze({

  /**
   * Identity Name field.
   * Standardizes the semantic name of any entity.
   */
  NAME_FIELD: (label = "Nombre", width = 12) => Object.freeze([
    { name: "nombre", type: "text", label: label, required: true, width: width, unique: true, gridOrder: 4 }
  ]),

  /**
   * Identity fields: user-friendly ID + status.
   * Universal for all business entities.
   * - lexical_id: prefix-acronym + consecutive (e.g. "PORT-0042"). Generated by Engine_DB.
   * - estado: lifecycle status flag ("Activo" | "Eliminado" | "Borrador").
   */
  SYSTEM_FIELDS: () => Object.freeze([
    {
      name: "lexical_id", type: "text", label: "ID", uiBehavior: "badge", readonly: true,
      helpText: "Generado automáticamente: ACRONIMO-CONSECUTIVO (ej. PORT-0042)", gridOrder: 3
    },
    { name: "estado", type: "hidden", defaultValue: "Activo" }
  ]),

  /**
   * Standalone status field for non-business entities (system/config tables)
   * that don't use lexical_id.
   */
  ESTADO_FIELD: () => Object.freeze([
    { name: "estado", type: "hidden", defaultValue: "Activo" }
  ]),

  /**
   * Industry-standard audit trail fields.
   * All hidden — managed exclusively by Engine_DB. Never rendered by FormEngine.
   * Provides full creation, modification, and soft-delete traceability.
   */
  AUDIT_FIELDS: () => Object.freeze([
    { name: "created_at", type: "hidden", readonly: true },
    { name: "created_by", type: "hidden", readonly: true },
    { name: "updated_at", type: "hidden", readonly: true },
    { name: "updated_by", type: "hidden", readonly: true },
    { name: "deleted_at", type: "hidden", readonly: true },
    { name: "deleted_by", type: "hidden", readonly: true }
  ]),

  /**
   * Optimistic locking version counter.
   * Incremented by Engine_DB on every write. Prevents lost-update on concurrent edits.
   * Default: 1 (first write).
   */
  VERSION_FIELD: () => Object.freeze([
    { name: "_version", type: "hidden", readonly: true, defaultValue: 1 }
  ]),

  /**
   * Standard graph topology section separator.
   * Returns a frozen single-element array (consistent with other FIELD_TEMPLATES factories).
   * Use with spread: ...FIELD_TEMPLATES.GRAPH_SEPARATOR()
   * @param {string} [label="Pertenencia Topológica (Grafo)"] - Section label
   */
  GRAPH_SEPARATOR: (label = "Pertenencia Topológica (Grafo)") => Object.freeze([
    { name: "separator_grafo", type: "divider", label, width: 12 }
  ])

});

var APP_SCHEMAS = {
  Taxonomia: {
    metadata: { prefix: 'TAXO', showInMenu: true, iconName: 'library-outline', color: 'tertiary', label: 'Taxonomías', titleField: 'nombre', idField: 'id_taxonomia', fkField: null },
    primaryKey: "id_taxonomia",
    titleField: "nombre",
    wizardConfig: true,
    stepDescriptions: {
      "Taxonomía de Producto": "Asigna un nombre descriptivo para comenzar. Te recomendamos utilizar el nombre del portafolio principal que vas a estructurar.",
      "Importar Equipos": "Carga la plantilla de equipos mediante URL o archivo de Google Sheets.",
      "Importar Personas": "Carga la plantilla de personas mediante URL o archivo de Google Sheets.",
      "Arquitectura de Portafolio": "Diseña la estructura utilizando el lienzo interactivo ubicado a la derecha."
    },
    hooks: {
      preSubmit: function (payload, contextId, action, isTempPk, internalRetryId) {
        let isActuallyCreate = action === 'create';
        if (!isActuallyCreate && internalRetryId && typeof window !== 'undefined' && window.DataStore) {
          const existing = window.DataStore.get('Taxonomia') || [];
          const match = existing.find(t => String(t.id_taxonomia) === String(internalRetryId));
          if (!match) isActuallyCreate = true;
        }
        if (isActuallyCreate || isTempPk) {
          payload.estado = 'Borrador';
        }
        if (!payload.id_taxonomia && contextId && contextId !== 'DRAFT_CTX') {
          payload.id_taxonomia = contextId;
        }
        return payload;
      }
    },
    fields: [
      { name: "id_taxonomia", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      { name: "nombre", type: "text", label: "Nombre de la Taxonomía", required: true, width: 12, section: "Taxonomía de Producto" },
      { name: "descripcion", type: "textarea", label: "Descripción", required: false, width: 12, section: "Taxonomía de Producto" },
      { name: "id_unidad_negocio", type: "hidden", relationType: "padre", targetEntity: "Unidad_Negocio", graphEntity: "Sys_Graph_Edges", valueField: "id_unidad_negocio", labelField: "nombre", isTemporalGraph: true, graphEdgeType: "TAXONOMIA_UNIDAD", topologyCardinality: "1:N", workspaceMode: false, required: false },
      { name: "info_equipos", type: "uiComponent", uiComponent: "bulk_importer", targetEntity: "Equipo", width: 12, section: "Importar Equipos" },
      { name: "info_personas", type: "uiComponent", uiComponent: "bulk_importer", targetEntity: "Persona", width: 12, section: "Importar Personas" },
      { name: "info_canvas", type: "divider", label: "Interactúa con el lienzo a tu derecha para modelar las capacidades y productos.", width: 12, section: "Arquitectura de Portafolio" }
    ]
  },
  Unidad_Negocio: {
    metadata: { prefix: 'UNDN', showInMenu: true, order: 1, iconName: 'business-outline', color: 'primary', label: 'Unidades de Negocio', titleField: 'nombre', idField: 'id_unidad_negocio', fkField: null },
    primaryKey: "id_unidad_negocio",
    topologyRules: TOPOLOGY_PRESETS.JERARQUICA_ESTRICTA_GRAPH_STD,
    fields: [
      { name: "id_unidad_negocio", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Unidad"),
      { name: "portafolios_vinculados", type: "relation", relationType: "hijo", targetEntity: "Portafolio", graphEntity: "Sys_Graph_Edges", valueField: "id_portafolio", labelField: "nombre", uiComponent: "searchable_multi", label: "Portafolios", isTemporalGraph: true, graphEdgeType: "UNIDAD_NEGOCIO_PORTAFOLIO", topologyCardinality: "1:N", width: 12 }
    ]
  },
  Portafolio: {
    uiConfig: { dashboardCard: { iconName: 'briefcase-outline', color: 'var(--ion-color-danger)' } },
    metadata: { prefix: 'PORT', showInMenu: true, order: 2, iconName: 'briefcase-outline', color: 'danger', label: 'Portafolios', titleField: 'nombre', idField: 'id_portafolio', fkField: null, maxListAttrs: 8 },
    topological_metadata: {
      ownerFields: ["director_id", "vp_id"],
      parentEntity: "Unidad_Negocio",
      parentField: "unidad_negocio_padre"
    },
    mutationInterceptors: ['AutoProvisionEntityRoles'],
    primaryKey: "id_portafolio",
    topologyRules: TOPOLOGY_PRESETS.JERARQUICA_ESTRICTA_GRAPH_STD,
    fields: [
      { name: "id_portafolio", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Portafolio"),
      { name: "gerente_portafolio_id", type: "relation", relationType: "padre", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", label: "Gerente de Portafolio", isTemporalGraph: true, graphEdgeType: "PORTAFOLIO_GERENTE", uiComponent: "searchable_single", valueField: "id_persona", labelField: "_nombre_completo", width: 12 },
      { name: "unidad_negocio_padre", type: "relation", relationType: "padre", targetEntity: "Unidad_Negocio", graphEntity: "Sys_Graph_Edges", valueField: "id_unidad_negocio", labelField: "nombre", uiComponent: "select_single", label: "Unidad de Negocio", isTemporalGraph: true, graphEdgeType: "UNIDAD_NEGOCIO_PORTAFOLIO", topologyCardinality: "1:N", width: 12, showInList: true },
      { name: "value_streams_vinculados", type: "relation", relationType: "hijo", targetEntity: "Value_Stream", graphEntity: "Sys_Graph_Edges", valueField: "id_value_stream", labelField: "nombre", uiComponent: "searchable_multi", label: "Value Streams", isTemporalGraph: true, graphEdgeType: "PORTAFOLIO_VALUE_STREAM", topologyCardinality: "N:M", width: 12 }
    ]
  },
  Dominio: {
    metadata: { prefix: 'DOMI', showInMenu: true, order: 3, iconName: 'globe-outline', color: 'primary', label: 'Dominios', titleField: 'nombre', idField: 'id_dominio', fkField: null, governancePolicy: 'exempt_from_strict_readonly' },
    primaryKey: "id_dominio",
    titleField: "nombre",
    topologyRules: TOPOLOGY_PRESETS.JERARQUICA_ESTRICTA_DOMAIN,
    fields: [
      { name: "id_dominio", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      { name: "id_externo", type: "text", label: "ID Externo", required: true, width: 6 },
      { name: "nivel_tipo", type: "number", label: "Nivel Tipo", required: false, readonly: true, width: 6 },
      { name: "orden_path", type: "text", label: "Orden Path", required: false, width: 12 },
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre (ES)", 6),
      { name: "nombre_ingles", type: "text", label: "Nombre (EN)", required: false, width: 6 },
      { name: "abreviacion", type: "text", label: "Abreviación", required: false, width: 6 },
      { name: "descripcion", type: "textarea", label: "Definición / Descripción", required: true, width: 12, showInList: false },
      { name: "contexto_completo_analisis", type: "textarea", label: "Contexto Análisis", required: false, width: 12, showInList: false },
      { name: "path_completo_es", type: "text", label: "Path Completo", required: false, width: 12 },
      { width: 12, name: "relaciones_padre", type: "relation", relationType: "padre", targetEntity: "Dominio", graphEntity: "Sys_Graph_Edges", valueField: "id_dominio", labelField: "nombre", uiComponent: "searchable_single", label: "Dominio Padre", isTemporalGraph: true, graphEdgeType: "DOMINIO_HIJO", topologyCardinality: "1:N", readonly: false },
      { width: 12, name: "relaciones_hijo", type: "relation", relationType: "hijo", targetEntity: "Dominio", graphEntity: "Sys_Graph_Edges", valueField: "id_dominio", labelField: "nombre", uiComponent: "searchable_multi", label: "Dominios Subordinados", isTemporalGraph: true, graphEdgeType: "DOMINIO_HIJO", topologyCardinality: "1:N", readonly: false }
    ]
  },
  Grupo_Productos: {
    metadata: { showInMenu: true, order: 4, iconName: 'layers-outline', color: 'dark', label: 'Grupos de Producto', titleField: 'nombre', idField: 'id_grupo_producto', fkField: { key: 'id_value_stream', label: 'Value Stream' } },
    topological_metadata: {
      ownerFields: ["group_manager_id"],
      parentEntity: "Value_Stream",
      parentField: "id_value_stream"
    },
    mutationInterceptors: ['AutoProvisionEntityRoles'],
    primaryKey: "id_grupo_producto",
    titleField: "nombre",
    topologyRules: TOPOLOGY_PRESETS.JERARQUICA_ESTRICTA_GRAPH_STD,
    fields: [
      { name: "id_grupo_producto", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre"),
      { name: "gerente_producto_id", type: "relation", relationType: "padre", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", label: "Gerente de Producto", isTemporalGraph: true, graphEdgeType: "GRUPO_PRODUCTO_GERENTE", uiComponent: "searchable_single", valueField: "id_persona", labelField: "_nombre_completo", width: 12 },
      { width: 12, name: "id_value_stream", type: "relation", relationType: "padre", targetEntity: "Value_Stream", graphEntity: "Sys_Graph_Edges", valueField: "id_value_stream", labelField: "nombre", uiComponent: "select_single", label: "Value Stream", isTemporalGraph: true, graphEdgeType: "VALUE_STREAM_GRUPO_PRODUCTO", topologyCardinality: "1:N", required: true },
      { width: 12, name: "productos_vinculados", type: "relation", relationType: "hijo", targetEntity: "Producto", graphEntity: "Sys_Graph_Edges", valueField: "id_producto", labelField: "nombre", uiComponent: "searchable_multi", label: "Productos", isTemporalGraph: true, graphEdgeType: "GRUPO_PRODUCTO_PRODUCTO", topologyCardinality: "1:N" },
      { width: 12, name: "equipos_asignados", type: "relation", relationType: "hijo", targetEntity: "Equipo", graphEntity: "Sys_Graph_Edges", valueField: "id_equipo", labelField: "nombre", uiComponent: "searchable_multi", label: "Equipos", isTemporalGraph: true, graphEdgeType: "GRUPO_PRODUCTO_EQUIPO", topologyCardinality: "1:N" }
    ]
  },
  Producto: {
    uiConfig: { dashboardCard: { iconName: 'cube-outline', color: 'var(--ion-color-tertiary)' } },
    metadata: { showInMenu: true, order: 5, iconName: 'cube-outline', color: 'tertiary', label: 'Productos', titleField: 'nombre', idField: 'id_producto', fkField: { key: 'id_grupo_producto', label: 'Grupo' } },
    topological_metadata: {
      ownerFields: ["rte_id", "pm_id", "agile_coach_id"],
      parentEntity: "Grupo_Productos",
      parentField: "id_grupo_producto"
    },
    primaryKey: "id_producto",
    titleField: "nombre",
    topologyRules: TOPOLOGY_PRESETS.JERARQUICA_ESTRICTA_GRAPH_STD,
    fields: [
      { name: "id_producto", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Producto"),
      { width: 12, name: "id_grupo_producto", type: "relation", relationType: "padre", targetEntity: "Grupo_Productos", graphEntity: "Sys_Graph_Edges", valueField: "id_grupo_producto", labelField: "nombre", uiComponent: "select_single", label: "Grupo de Producto", isTemporalGraph: true, graphEdgeType: "GRUPO_PRODUCTO_PRODUCTO", topologyCardinality: "1:N", required: true }
    ]
  },
  Capacidad: {
    metadata: { showInMenu: true, order: 6, iconName: 'layers-outline', color: 'warning', label: 'Capacidades', titleField: 'nombre', idField: 'id_capacidad', fkField: null, governancePolicy: 'exempt_from_strict_readonly' },
    topological_metadata: {
      parentEntity: "Capacidad",
      parentField: "id_dominio_padre"
    },
    primaryKey: "id_capacidad",
    titleField: "nombre",
    topologyRules: TOPOLOGY_PRESETS.JERARQUICA_ESTRICTA_DOMAIN,
    fields: [
      { name: "id_capacidad", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      { name: "id_externo", type: "text", label: "ID Externo", required: false, width: 6 },
      { name: "nivel_tipo", type: "number", label: "Nivel Tipo", required: false, readonly: true, width: 6 },
      { name: "orden_path", type: "text", label: "Orden Path", required: false, width: 12 },
      ...FIELD_TEMPLATES.NAME_FIELD("Macrocapacidad"),
      { name: "nombre_ingles", type: "text", label: "Nombre Inglés", required: false, width: 12 },
      { name: "abreviacion", type: "text", label: "Abreviación", required: false, width: 6 },
      { name: "descripcion", type: "textarea", label: "Descripción", required: false, width: 12, showInList: false },
      { name: "contexto_completo_analisis", type: "textarea", label: "Contexto Análisis", required: false, width: 12, showInList: false },
      { name: "path_completo_es", type: "text", label: "Path Completo", required: false, width: 12 },
      { name: "id_dominio_padre", type: "relation", relationType: "padre", targetEntity: "Capacidad", graphEntity: "Sys_Graph_Edges", label: "Capacidad Padre", isTemporalGraph: true, topologyCardinality: "1:N", graphEdgeType: "CAPACIDAD_HIJO", required: false, width: 12, uiComponent: "searchable_single", valueField: "id_capacidad", labelField: "nombre" },
      { name: "capacidades_hijas", type: "relation", relationType: "hijo", targetEntity: "Capacidad", graphEntity: "Sys_Graph_Edges", label: "Capacidades Subordinadas", isTemporalGraph: true, topologyCardinality: "1:N", graphEdgeType: "CAPACIDAD_HIJO", required: false, width: 12, uiComponent: "searchable_multi", valueField: "id_capacidad", labelField: "nombre" }
    ]
  },
  Equipo: {
    uiConfig: { dashboardCard: { iconName: 'people-outline', color: 'var(--ion-color-success)' } },
    metadata: { showInMenu: true, order: 7, iconName: 'people-outline', color: 'success', label: 'Equipos', titleField: 'nombre', idField: 'id_equipo', fkField: { key: 'id_grupo_producto', label: 'Grupo de Producto' } },
    topological_metadata: {
      ownerFields: ["scrum_master_id", "product_owner_id"],
      parentEntity: "Grupo_Productos",
      parentField: "id_grupo_producto"
    },
    mutationInterceptors: ['AutoProvisionEntityRoles'],
    primaryKey: "id_equipo",
    fields: [
      { name: "id_equipo", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      { name: "id_grupo_producto", type: "relation", relationType: "padre", targetEntity: "Grupo_Productos", graphEntity: "Sys_Graph_Edges", label: "Grupo de Producto", isTemporalGraph: true, graphEdgeType: "GRUPO_PRODUCTO_EQUIPO", required: true, width: 6, uiComponent: "select_single", valueField: "id_grupo_producto", labelField: "nombre" },
      { name: "personas_asignadas", type: "relation", relationType: "hijo", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", isTemporalGraph: true, graphEdgeType: "PERSONA_EQUIPO", label: "Personas Asignadas (Célula Base)", virtual: true, uiBehavior: "subgrid", allowedRoles: ["Developer", "Tester", "Tech Lead"], width: 12 },
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Equipo", 6),
      { name: "seudonimo", type: "text", label: "Seudónimo", required: false, width: 6 },
      { name: "formas_de_trabajo", type: "select", label: "Formas de Trabajo", required: true, width: 6, options: ["Scrum", "Kanban", "Híbrido"] },
      { name: "proposito", type: "textarea", label: "Propósito", required: false, width: 12 },
      { name: "scrum_master_id", type: "relation", relationType: "padre", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", label: "Scrum Master / Team Coach", isTemporalGraph: true, graphEdgeType: "EQUIPO_SM", uiComponent: "select_single", valueField: "email", labelField: "_nombre_completo", required: false, width: 6 },
      { name: "product_owner_id", type: "relation", relationType: "padre", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", label: "Dueño de Producto", isTemporalGraph: true, graphEdgeType: "EQUIPO_PO", uiComponent: "select_single", valueField: "email", labelField: "_nombre_completo", required: false, width: 6 },
      { name: "rte_id", type: "relation", relationType: "padre", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", label: "Release Train Engineer (RTE)", isTemporalGraph: true, graphEdgeType: "EQUIPO_RTE", uiComponent: "select_single", valueField: "email", labelField: "_nombre_completo", required: false, width: 12 },
      { name: "url_tablero_trabajo", type: "url", label: "URL Tablero de Trabajo", required: false, width: 12 }
    ]
  },
  Persona: {
    uiConfig: {
      dashboardCard: {
        iconName: 'person-outline',
        color: 'var(--ion-color-warning)',
        avatarField: 'avatar',
        subtitleFields: [
          { field: 'email', icon: 'mail-outline' },
          { field: 'departamento', icon: 'business-outline' }
        ]
      }
    },
    computedFields: [
      { name: '_nombre_completo', concat: ['nombre', 'apellidos'], separator: ' ', fallback: ['email', 'id_persona'] }
    ],
    metadata: { showInMenu: true, order: 8, iconName: 'person-outline', color: 'warning', label: 'Personas', titleField: '_nombre_completo', idField: 'id_persona', fkField: null },
    primaryKey: "id_persona",
    mutationInterceptors: ['AutoProvisionCargo', 'AutoProvisionLiderDirecto'],
    relationalProvisioners: [
      {
        field: 'roles_asignados',
        targetEntity: 'Rol',
        idField: 'id_rol',
        edgeType: 'PERSONA_ROL',
        stubPrefix: 'ROL-',
        extraStubFields: { nivel: "Nivel Base" }
      },
      {
        field: 'equipo',
        targetEntity: 'Equipo',
        idField: 'id_equipo',
        edgeType: 'PERSONA_EQUIPO',
        stubPrefix: 'EQUI-'
      }
    ],
    topologyRules: TOPOLOGY_PRESETS.JERARQUICA_PERSONA,
    fields: [
      { name: "id_persona", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),

      { name: "separator_1", type: "divider", label: "Datos Personales", icon: "person-outline", width: 12 },
      { name: "nombre", type: "text", label: "Nombre(s)", required: true, width: 6, validators: ["minLength:2"], triggers_workspace_resolve: true },
      { name: "apellidos", type: "text", label: "Apellidos", required: true, width: 6, validators: ["minLength:2"] },

      { name: "separator_2", type: "divider", label: "Datos de Contacto", icon: "mail-outline", width: 12 },
      { name: "email", type: "email", primaryKey: false, label: "Correo Corporativo", required: true, width: 12, validators: ["regex:^[a-zA-Z0-9._%+-]+@(coppel\\.com|bancoppel\\.com|kairosds\\.com|nttdata\\.com)$"], triggers_workspace_resolve: true, unique: true },
      { name: "telefono", type: "tel", label: "Teléfono", required: false, width: 12 },

      { name: "separator_4", type: "divider", label: "Datos Agilidad", icon: "git-network-outline", width: 12 },
      { name: "roles_asignados", type: "relation", relationType: "padre", targetEntity: "Rol", graphEntity: "Sys_Graph_Edges", label: "Roles Organizacionales", isTemporalGraph: true, graphEdgeType: "PERSONA_ROL", valueField: "id_rol", labelField: "nombre", uiComponent: "searchable_multi", topologyCardinality: "M:N", width: 12, allowInETL: true },
      { name: "equipo", type: "relation", relationType: "padre", targetEntity: "Equipo", graphEntity: "Sys_Graph_Edges", label: "Equipos Asignados", isTemporalGraph: true, graphEdgeType: "PERSONA_EQUIPO", required: false, width: 12, uiComponent: "searchable_multi", topologyCardinality: "M:N", valueField: "id_equipo", labelField: "nombre", allowInETL: true },
      { name: "porcentaje_asignacion", type: "select", label: "Asignación", options: ["Full Time", "Part Time", "Por Proyecto"], width: 12, excludeFromETL: true },

      { name: "separator_3", type: "divider", label: "Datos Empresariales", icon: "business-outline", width: 12 },
      { name: "unidad_negocio", type: "lookup", lookupTarget: "Unidad_Negocio", label: "Unidad de Negocio", required: true, width: 12 },
      { name: "departamento", type: "text", label: "Departamento", required: true, width: 12, excludeFromETL: true },
      { name: "id_cargo", type: "relation", relationType: "padre", targetEntity: "Cargo", graphEntity: "Sys_Graph_Edges", label: "Cargo Oficial", isTemporalGraph: true, topologyCardinality: "1:N", graphEdgeType: "CARGO_PERSONA", uiComponent: "select_single", valueField: "id_cargo", labelField: "nombre", required: true, width: 12 },
      { name: "cargo", type: "hidden", label: "Cargo Oficial Workspace (Plano)" },
      { name: "lider_directo", type: "relation", relationType: "padre", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", valueField: "id_persona", labelField: "_nombre_completo", topologyCardinality: "1:N", isTemporalGraph: true, graphEdgeType: "PERSONA_LIDER_DIRECTO", label: "Líder Directo", required: false, width: 12, uiComponent: "select_single" },
      { name: "centro_costo", type: "text", label: "Centro de Costos", required: true, width: 6, excludeFromETL: true },
      { name: "numero_empleado", type: "number", label: "Número de Empleado", required: true, width: 6, validators: ["regex:^\\d{8}$"], unique: true, excludeFromETL: true },
      { name: "modalidad", type: "select", label: "Modalidad", options: ["Presencial", "Virtual", "Híbrido"], required: true, width: 6 },
      { name: "esquema", type: "select", label: "Esquema Laboral", options: ["Interno", "Externo"], required: true, width: 6 },
      { name: "proveedor", type: "text", label: "Empresa Contratante", required: true, width: 6 },
      { name: "ubicacion", type: "text", label: "Ubicación Geográfica", required: false, width: 12 },
      { name: "estado_geo", type: "text", label: "Estado", required: false, width: 6 },
      { name: "ciudad", type: "text", label: "Ciudad", required: false, width: 6 },

      { name: "separator_5", type: "divider", label: "Control de Accesos (Admin)", width: 12, abacRule: { action: 'update', target: 'Sys_Permissions' } },
      { name: "id_rol", type: "select", label: "Rol de Autorización", required: false, width: 12, lookupSource: "getSysRolesOptions", abacRule: { action: 'update', target: 'Sys_Permissions' }, excludeFromETL: true },
      { name: "workspace_sync_status", type: "hidden", label: "Estado Sincronización WS" },
      { name: "avatar", type: "hidden", label: "Avatar URL" }
    ]
  },
  Cargo: {
    metadata: { prefix: 'CARG', showInMenu: true, order: 8, iconName: 'id-card-outline', color: 'tertiary', label: 'Cargos y Posiciones', titleField: 'nombre', idField: 'id_cargo', fkField: null },
    primaryKey: "id_cargo",
    titleField: "nombre",
    fields: [
      { name: "id_cargo", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      { name: "id_externo_workspace", type: "text", label: "ID Workspace (Ext)", required: false, width: 12, unique: true, readonly: true, showInForm: false, helpText: "Generado auto. Se oculta del motor form ya que no requiere captura humana." },
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Cargo"),
      { name: "personas_asignadas", type: "relation", relationType: "hijo", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", label: "Personas Asignadas", isTemporalGraph: true, graphEdgeType: "CARGO_PERSONA", valueField: "id_persona", labelField: "_nombre_completo", uiComponent: "searchable_multi", topologyCardinality: "1:N", width: 12 }
    ]
  },
  Rol: {
    metadata: { prefix: 'ROLE', showInMenu: true, order: 9, iconName: 'shirt-outline', color: 'primary', label: 'Roles', titleField: 'nombre', idField: 'id_rol', fkField: null },
    primaryKey: "id_rol",
    titleField: "nombre",
    fields: [
      { name: "id_rol", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Rol", 6),
      { name: "nombre_ingles", type: "text", label: "Nombre en Inglés", required: false, width: 6 },
      { name: "color_icono", type: "select", options: ["primary", "secondary", "tertiary", "success", "warning", "danger", "dark", "medium", "light"], label: "Color del Ícono", width: 6 },
      { name: "especialidad", type: "select", options: ["TI", "Negocio", "Producto", "Agilidad"], label: "Área de Gestión / Especialidad", width: 12, placeholder: "Seleccione..." },
      { name: "descripcion", type: "textarea", label: "Descripción", required: false, width: 12, showInList: false },
      { name: "personas_asignadas", type: "relation", relationType: "hijo", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", label: "Personas Asignadas", isTemporalGraph: true, graphEdgeType: "PERSONA_ROL", valueField: "id_persona", labelField: "_nombre_completo", uiComponent: "searchable_multi", topologyCardinality: "M:N", width: 12 }
    ]
  },
  Sys_Graph_Edges: {
    metadata: { showInMenu: false, order: 10, iconName: 'git-network-outline', color: 'primary', label: 'Grafo Universal Temporal', titleField: 'tipo_relacion', idField: 'id_relacion', fkField: { key: 'id_nodo_padre', label: 'Nodo Padre' } },
    primaryKey: "id_relacion",
    fields: [
      { name: "id_relacion", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      { name: "id_nodo_padre", type: "text", required: true, width: 6 },
      { name: "id_nodo_hijo", type: "text", required: true, width: 6 },
      { name: "tipo_relacion", type: "text", required: true, width: 6 },
      { name: "valido_desde", type: "hidden" },
      { name: "valido_hasta", type: "hidden" },
      { name: "es_version_actual", type: "hidden", defaultValue: true },
      { name: "peso_capacidad", type: "number", label: "Dedicación (%)", defaultValue: 100, width: 6, validators: ["min:0", "max:100"] },
      { name: "contexto_id", type: "text", required: false, label: "ID Contexto/Borrador", showInList: false },
      { name: "metadata_config", type: "textarea", label: "Configuración Adicional (JSON)", required: false, width: 12, showInList: false, validators: ["json"] }
    ]
  },
  Sys_Roles: {
    metadata: { prefix: 'SROL', showInMenu: false, order: 90, iconName: 'shield-half-outline', color: 'danger', label: 'Seguridad: Roles', titleField: 'nombre', idField: 'id_rol', fkField: null },
    primaryKey: "id_rol",
    fields: [
      { name: "id_rol", type: "text", primaryKey: true, readonly: true, label: "ID Rol", width: 12 },
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Rol", 6),
      { name: "descripcion", type: "textarea", label: "Descripción", required: false, width: 12, showInList: false }
    ]
  },
  Config_Typography: {
    metadata: { showInMenu: false, order: 92, iconName: 'text-outline', color: 'medium', label: 'Temas Tipográficos', titleField: 'nombre', idField: 'id_tipografia', fkField: null },
    primaryKey: "id_tipografia",
    fields: [
      { name: "id_tipografia", type: "text", primaryKey: true, readonly: true, label: "ID Pack", width: 12 },
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Pack"),
      { name: "font_display", type: "select", label: "Ultra Título (.text-display)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "El texto con el que representamos frases, conceptos o ideas urgentes o de gran importancia." },

      { name: "div_headers", type: "divider", label: "Headers 1, 2, 3", width: 12 },
      { name: "font_h1", type: "select", label: "Título Principal (h1)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "El título más importante de una página o sección." },
      { name: "font_h2", type: "select", label: "Título Secundario (h2)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "Un título de menor importancia que el título principal." },
      { name: "font_h3", type: "select", label: "Título Terciario (h3)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "Un título de menor importancia que el título secundario." },

      { name: "div_subs", type: "divider", label: "SubHeaders", width: 12 },
      { name: "font_sub", type: "select", label: "Subtítulos (.text-sub)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "Un texto breve que complementa y expande un título." },

      { name: "div_body", type: "divider", label: "Body & Small", width: 12 },
      { name: "font_body", type: "select", label: "Texto Cuerpo (body)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "Párrafos largos, artículos, descripciones." },
      { name: "font_mini", type: "select", label: "Miniaturas (.text-mini)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "Un texto de menor importancia que el texto principal." },

      { name: "div_caption", type: "divider", label: "Caption & Action", width: 12 },
      { name: "font_caption", type: "select", label: "Leyendas (.text-caption)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "Un texto breve que describe una imagen, gráfico o tabla." },
      { name: "font_action", type: "select", label: "Acciones (.text-action)", required: true, width: 6, options: ["Poppins, sans-serif", "Playfair Display, serif", "Inter, sans-serif", "Roboto, sans-serif", "Montserrat, sans-serif"], helpText: "Botones, enlaces y llamados a la acción." },

      { name: "div_math", type: "divider", label: "Escala y Proporciones", width: 12 },

      { name: "base_size", type: "select", label: "Tamaño Base (Body Px)", required: true, width: 6, options: ["12px", "14px", "16px", "18px"], defaultValue: "16px", helpText: "Impacta directamente el tamaño de los párrafos y textos base." },
      { name: "scale_ratio", type: "select", label: "Multiplicador de Escala", required: true, width: 6, options: ["1.125 (Major Second)", "1.200 (Minor Third)", "1.250 (Major Third)", "1.333 (Perfect Fourth)", "1.618 (Golden Ratio)"], defaultValue: "1.250 (Major Third)", helpText: "Define qué tan rápido crecen los títulos en proporción al texto base." },
      { name: "heading_weight", type: "select", label: "Peso de Títulos (Weight)", required: true, width: 6, options: ["400", "500", "600", "700", "800"], defaultValue: "600", helpText: "Controla el grosor global de todos los Títulos y Subtítulos." },
      { name: "heading_transform", type: "select", label: "Mayúsculas/Minúsculas", required: true, width: 6, options: ["none", "uppercase", "capitalize", "lowercase"], defaultValue: "none", helpText: "Transforma automáticamente la capitalización de los títulos." }
    ]
  },
  Sys_Permissions: {
    metadata: { prefix: 'SPRM', showInMenu: false, order: 91, iconName: 'key-outline', color: 'danger', label: 'Seguridad: Permisos ABAC', titleField: 'schema_destino', idField: 'id_permiso', fkField: { key: 'id_rol', label: 'Rol Base' } },
    primaryKey: "id_permiso",
    fields: [
      { name: "id_permiso", type: "text", primaryKey: true, readonly: true, label: "ID Permiso", width: 12 },
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      { name: "id_rol", type: "select", label: "Rol Organizacional", required: true, width: 6, lookupSource: "getSysRolesOptions" },
      { name: "schema_destino", type: "select", label: "Entidad del Sistema", required: true, width: 6, options: ["Portafolio", "Dominio", "Grupo_Productos", "Producto", "Capacidad", "Unidad_Negocio", "Equipo", "Persona", "Sys_Graph_Edges", "Sys_Roles", "Sys_Permissions", "Config_Typography", "Config_Workspace"] },
      { name: "nivel_acceso", type: "select", label: "Nivel de Acceso", required: true, width: 12, options: ["ALL (Admin Total)", "OWNER_ONLY (Solo propios)", "MEMBER_ONLY (Siendo Miembro)", "READ_ONLY (Solo lectura)", "NONE (Denegado)"] }
    ]
  },
  // [E31-S31.4] Duplicate Sys_Graph_Edges key removed. Canonical definition ~line 282.

  Value_Stream: {
    uiConfig: { dashboardCard: { iconName: 'swap-horizontal-outline', color: 'var(--ion-color-tertiary)' } },
    metadata: { prefix: 'VSTR', showInMenu: true, order: 8, iconName: 'swap-horizontal-outline', color: 'tertiary', label: 'Value Streams', titleField: 'nombre', idField: 'id_value_stream', fkField: null, maxListAttrs: 8 },
    topological_metadata: {
      parentEntity: "Portafolio",
      parentField: "portafolios_padre"
    },
    mutationInterceptors: ['AutoProvisionEntityRoles'],
    primaryKey: "id_value_stream",
    topologyRules: TOPOLOGY_PRESETS.JERARQUICA_ESTRICTA_GRAPH_STD,
    fields: [
      { name: "id_value_stream", type: "hidden", primaryKey: true },
      ...FIELD_TEMPLATES.SYSTEM_FIELDS(),
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      ...FIELD_TEMPLATES.VERSION_FIELD(),
      ...FIELD_TEMPLATES.NAME_FIELD("Nombre de Value Stream"),
      { name: "descripcion", type: "text", label: "Descripción / Propósito", required: false, width: 12 },
      { name: "dueno_vs_id", type: "relation", relationType: "padre", targetEntity: "Persona", graphEntity: "Sys_Graph_Edges", label: "Dueño del Value Stream", isTemporalGraph: true, graphEdgeType: "VS_DUENO", uiComponent: "searchable_single", valueField: "id_persona", labelField: "_nombre_completo", width: 12 },
      { width: 12, name: "portafolios_padre", type: "relation", relationType: "padre", targetEntity: "Portafolio", graphEntity: "Sys_Graph_Edges", valueField: "id_portafolio", labelField: "nombre", uiComponent: "searchable_multi", label: "Portafolios", isTemporalGraph: true, graphEdgeType: "PORTAFOLIO_VALUE_STREAM", topologyCardinality: "N:M", required: true },
      { width: 12, name: "grupos_productos_vinculados", type: "relation", relationType: "hijo", targetEntity: "Grupo_Productos", graphEntity: "Sys_Graph_Edges", valueField: "id_grupo_producto", labelField: "nombre", uiComponent: "searchable_multi", label: "Grupos de Productos", isTemporalGraph: true, graphEdgeType: "VALUE_STREAM_GRUPO_PRODUCTO", topologyCardinality: "1:N" }
    ]
  },
  Config_Workspace: {
    metadata: { showInMenu: true, order: 93, iconName: 'business-outline', color: 'primary', label: 'Seguridad: Workspaces', titleField: 'dominio_principal', idField: 'id_workspace', fkField: null, requireStrictMatrixAccess: true },
    primaryKey: "id_workspace",
    fields: [
      { name: "id_workspace", type: "text", primaryKey: true, readonly: true, label: "ID Workspace", width: 12 },
      ...FIELD_TEMPLATES.ESTADO_FIELD(),
      ...FIELD_TEMPLATES.AUDIT_FIELDS(),
      { name: "dominio_principal", type: "text", label: "Dominio Principal", required: true, width: 6, helpText: "Ejemplo: @tenantA.com" },
      { name: "alias_alternativos", type: "text", label: "Alias Soportados (CSV)", required: false, width: 6, helpText: "Ejemplo: @tenantA.com,@tenantB.com" },
      { name: "activar_consulta_directorio", type: "boolean", label: "Consultar Workspace", required: false, width: 6, defaultValue: false, helpText: "Activa la sincronización de identidades." },
      { name: "webhook_url", type: "text", label: "Webhook URL (Microservicio)", required: false, width: 12, helpText: "URL del Apps Script desplegado por el administrador del dominio." },
      { name: "webhook_secret", type: "text", label: "Webhook Token (Secreto)", required: false, width: 6, helpText: "Token de autorización para consumir el microservicio." },
      { name: "setup_guide", type: "uiComponent", uiComponent: "microservice_setup", width: 12 }
    ]
  },
  // [S60/E6] Config_System: Entidad especial de configuración del sistema.
  // Persiste en PropertiesService (local al tenant) mediante Adapter_Config.
  // NO usa Google Sheets. Routing gestionado por Engine_DB via metadata.adapter.
  Config_System: {
    metadata: {
      adapter: 'config',
      showInMenu: false,
      showInSchemaStudio: false,
      order: 99,
      iconName: 'settings-outline',
      color: 'medium',
      label: 'Configuración del Sistema',
      section: 'ADMINISTRACIÓN',
      titleField: 'tenant_name',
      idField: 'config_id',
      fkField: null,
      requireStrictMatrixAccess: true
    },
    primaryKey: 'config_id',
    fields: [
      { name: 'config_id', type: 'text', primaryKey: true, readonly: true, label: 'ID Configuración', width: 6 },
      { name: 'tenant_name', type: 'text', label: 'Nombre del Tenant', required: true, width: 6,
        helpText: 'Identificador White-Label de esta instancia. Ej: Tenant A' },
      { name: 'db_adapter_id', type: 'select', label: 'Adaptador de Base de Datos', required: true, width: 6,
        options: [
          { value: 'sheets', label: 'Google Sheets' },
          { value: 'clouddb', label: 'Cloud Database' }
        ],
        helpText: 'Motor de almacenamiento de datos activo para este tenant.' },
      { name: 'spreadsheet_id', type: 'text', label: 'ID de Google Sheet (Base de Datos)', required: false, width: 12,
        helpText: 'ID del archivo Google Sheets que actúa como base de datos compartida entre tenants.' },
      { name: 'allowed_domains', type: 'text', label: 'Dominios SSO Permitidos (CSV)', required: false, width: 6,
        helpText: 'Correos permitidos para acceder al sistema. Ej: @tenantA.com,@tenantB.com' },
      { name: 'app_title', type: 'text', label: 'Título de la Aplicación', required: false, width: 6,
        helpText: 'Texto que aparece en la pestaña del navegador.' },
      { name: 'favicon_url', type: 'text', label: 'URL del Favicon', required: false, width: 12,
        helpText: 'URL pública del ícono de la aplicación (favicon).' }
    ]
  },
  _UI_CONFIG: {
    badgeMap: {
      'activo': 'activo', 'borrador': 'borrador', 'en-revis-n': 'en-revision', 'en-revision': 'en-revision',
      'tier-1-cr-tico': 'tier-1-critico', 'tier-1-critico': 'tier-1-critico',
      'tier-2-alto': 'tier-2-alto', 'tier-3-medio': 'tier-3-medio', 'tier-4-bajo': 'tier-4-bajo',
      'saas': 'saas', 'marketplace': 'marketplace', 'b2b': 'b2b', 'b2c': 'b2c', 'transaccional': 'transaccional',
      'all-admin-total': 'danger', 'owner-only-solo-propios': 'primary', 'member-only-siendo-miembro': 'secondary', 'read-only-solo-lectura': 'medium', 'none-denegado': 'light'
    }
  }
};

function getAppSchema(entityName) {
  const isTaxonomiaContext = typeof window !== 'undefined' && window.taxonomiaContext;

  const applyGovernance = (schema) => {
    if (!schema || !schema.fields) return schema;

    // Deep clone the fields array to avoid mutating global definition
    const clonedSchema = Object.assign({}, schema);
    clonedSchema.fields = schema.fields.map(field => {
      // E55 Governance: Topological fields are readonly
      if (field.type === 'relation' && field.graphEntity === 'Sys_Graph_Edges') {
        // Schema-Driven Governance Exemption (S57.4)
        const isExemptEntity = schema.metadata && schema.metadata.governancePolicy === 'exempt_from_strict_readonly';
        
        if (!isTaxonomiaContext && !isExemptEntity) {
          const clonedField = Object.assign({}, field);
          clonedField.readonly = true;
          clonedField.helpText = (clonedField.helpText ? clonedField.helpText + ' ' : '') + '(Solo lectura: Gestionado vía Canvas de Taxonomía)';
          return clonedField;
        }
      }
      return field;
    });
    return clonedSchema;
  };

  if (entityName) {
    return applyGovernance(APP_SCHEMAS[entityName]);
  } else {
    const clonedSchemas = {};
    for (const key in APP_SCHEMAS) {
      if (key !== '_UI_CONFIG' && APP_SCHEMAS[key] && APP_SCHEMAS[key].fields) {
        clonedSchemas[key] = applyGovernance(APP_SCHEMAS[key]);
      } else {
        clonedSchemas[key] = APP_SCHEMAS[key];
      }
    }
    return clonedSchemas;
  }
}

/**
 * Epic E8: Safe getter for topology rules. Returns the configured rules
 * for the entity if available, otherwise returns a safe default (FLAT).
 * Prevents downstream failures for legacy entities.
 */
function getEntityTopologyRules(entityName) {
  const schema = getAppSchema(entityName);
  if (schema && schema.topologyRules) {
    return schema.topologyRules;
  }
  // Safe Fallback defaults
  return {
    topologyType: "FLAT",
    levelFiltering: false,
    strictLevelJumps: false,
    rootRequiresNoParent: false,
    allowOrphanStealing: false,
    maxDepth: 0,
    deletionStrategy: "ORPHAN", // Always default to a safe setting (no cascading)
    siblingCollisionCheck: false,
    scd2Enabled: false,
    preventCycles: false
  };
}

if (typeof module !== 'undefined') {
  module.exports = { APP_SCHEMAS, TOPOLOGY_PRESETS, FIELD_TEMPLATES, getAppSchema, getEntityTopologyRules };
}

// ─── [E31] Admin GAS endpoints ───────────────────────────────────────────────
// Requires: Adapter_Sheets_Provisioner.gs (shares GAS global scope)
// These endpoints are now maintained in API_Admin.gs for SRP.
// See API_Admin.gs for getSchemaProvisioningStatus() and runSchemaReconcile().

